### ISSUE TITLE
Collections not adhering to sort order after initial plugin run

### ISSUE THREAD

**Issue by BoHoliday** [lostb1t/jellyfin-plugin-collection-import#2]
I have my mdblists set to Random for the sort order, so in theory, each time the plugin runs, it should sort the items in a collection in a different order. However, the sort order is not utilized by the plugin after the initial run. Each subsequent run simply adds items if needed.

Would it be possible to add a function to delete all items in each collection before the collection is populated again on each run?

**Comment by lostb1t** [comment]
It already clears existing items when updating a collection for this purpose.

When you say random, do you mean the upstream mdblist is soeted randomly? do you have an example list?

**Comment by lostb1t** [comment]
@BoHoliday fixed in 0.36

**Comment by lostb1t** [comment]
@BoHoliday fixed in 0.36
